# Generated by Django 5.2.14 on 2026-07-18 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EngineSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("schema_version", models.CharField(default="1", max_length=32)),
                ("generated_at", models.DateTimeField()),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("source_hash", models.CharField(max_length=64, unique=True)),
                (
                    "bundle_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "engine_git_sha",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("counts_json", models.JSONField(default=dict)),
                ("headers_json", models.JSONField(default=dict)),
                ("refuter_status", models.TextField(blank=True, default="")),
                (
                    "champion_status",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("champion_json", models.JSONField(default=dict)),
                ("manifest_json", models.JSONField(default=dict)),
                ("stale", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-imported_at"],
                "indexes": [
                    models.Index(
                        fields=["active", "-imported_at"],
                        name="workspace_e_active_eec720_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("active",),
                        name="workspace_one_active_snapshot",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEWING", "Reviewing"),
                            ("READY", "Ready"),
                            ("FROZEN", "Frozen"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "bundle_path",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "bundle_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "db_snapshot_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("decision_hashes_json", models.JSONField(default=dict)),
                ("engine_manifest_json", models.JSONField(default=dict)),
                (
                    "engine_git_sha",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("reviewer_identities_json", models.JSONField(default=list)),
                ("final_artifact_hashes_json", models.JSONField(default=dict)),
                ("transition_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("frozen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releases",
                        to="workspace.enginesnapshot",
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="workspace.release",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CorrectionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("finding_key", models.CharField(max_length=64)),
                ("queue", models.CharField(max_length=16)),
                ("explanation", models.TextField()),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="workspace.correctionrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["requested_at"],
                "indexes": [
                    models.Index(
                        fields=["finding_key", "-requested_at"],
                        name="workspace_c_finding_6fa10c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EngineAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("refresh", "Refresh"),
                            ("replay", "Replay"),
                            ("run", "Run"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("arguments_json", models.JSONField(default=dict)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lease_owner",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("stdout", models.TextField(blank=True, default="")),
                ("result_hashes_json", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "requested_at"],
                        name="workspace_e_status_f372a7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EvidenceRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("row_json", models.JSONField()),
                ("finding_key", models.CharField(max_length=64)),
                (
                    "proof_asset",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("blocked", models.BooleanField(default=False)),
                ("source_hash", models.CharField(max_length=64)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_rows",
                        to="workspace.enginesnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "indexes": [
                    models.Index(
                        fields=["snapshot", "finding_key"],
                        name="workspace_e_snapsho_040a17_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "finding_key"),
                        name="workspace_evidence_snapshot_finding_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FindingDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=255)),
                ("reviewer_role", models.CharField(max_length=32)),
                ("reviewed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("authoritative_file_hash", models.CharField(max_length=64)),
                ("writer_receipt_json", models.JSONField(default=dict)),
                ("finding_key", models.CharField(max_length=64)),
                (
                    "queue",
                    models.CharField(
                        choices=[
                            ("new", "NEW"),
                            ("known", "KNOWN"),
                            ("absence", "Absence"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "review_stage",
                    models.CharField(
                        choices=[
                            ("citation", "Citation"),
                            ("mapping", "Mapping"),
                            ("status", "Status"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=16,
                    ),
                ),
                ("citation_checked", models.BooleanField(default=False)),
                ("mapping_checked", models.BooleanField(default=False)),
                ("status_checked", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="workspace.findingdecision",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["finding_key", "review_stage", "-created_at"],
                        name="workspace_f_finding_d9f1f4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RecallDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=255)),
                ("reviewer_role", models.CharField(max_length=32)),
                ("reviewed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("authoritative_file_hash", models.CharField(max_length=64)),
                ("writer_receipt_json", models.JSONField(default=dict)),
                ("recall_key", models.CharField(max_length=64)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("REAL_MISS", "Real miss"),
                            ("GOLD_WRONG", "Gold wrong"),
                            ("GOLD_AMBIGUOUS", "Gold ambiguous"),
                            ("CORRECT_ABSTENTION", "Correct abstention"),
                            ("NEEDS_CORRECTION", "Needs correction"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reasoning", models.TextField(blank=True, default="")),
                (
                    "official_source_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="workspace.recalldecision",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["recall_key", "-created_at"],
                        name="workspace_r_recall__04fdae_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReviewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "queue",
                    models.CharField(
                        choices=[
                            ("new", "NEW"),
                            ("absence", "Absence"),
                            ("recall", "Recall"),
                            ("zone3", "Zone 3"),
                            ("known", "KNOWN"),
                        ],
                        max_length=16,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("row_json", models.JSONField()),
                ("stable_key", models.CharField(blank=True, default="", max_length=64)),
                (
                    "finding_key",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("blocked", models.BooleanField(default=False)),
                ("block_reason", models.TextField(blank=True, default="")),
                ("source_hash", models.CharField(max_length=64)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_items",
                        to="workspace.enginesnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "indexes": [
                    models.Index(
                        fields=["snapshot", "queue", "position"],
                        name="workspace_r_snapsho_09d136_idx",
                    ),
                    models.Index(
                        fields=["snapshot", "finding_key"],
                        name="workspace_r_snapsho_cd4bbc_idx",
                    ),
                    models.Index(
                        fields=["snapshot", "stable_key"],
                        name="workspace_r_snapsho_48d0a5_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "queue", "position"),
                        name="workspace_review_item_position_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RunRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_name", models.CharField(max_length=80)),
                ("envelope_json", models.JSONField()),
                ("cost_json", models.JSONField(default=dict)),
                ("source_hash", models.CharField(max_length=64)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_records",
                        to="workspace.enginesnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["run_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "run_name"),
                        name="workspace_run_snapshot_name_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Zone3Decision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=255)),
                ("reviewer_role", models.CharField(max_length=32)),
                ("reviewed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("authoritative_file_hash", models.CharField(max_length=64)),
                ("writer_receipt_json", models.JSONField(default=dict)),
                ("score_key", models.CharField(max_length=64)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("overridden", "Overridden"),
                        ],
                        max_length=16,
                    ),
                ),
                ("score", models.DecimalField(decimal_places=1, max_digits=2)),
                ("reasoning", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="workspace.zone3decision",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["score_key", "-created_at"],
                        name="workspace_z_score_k_43e822_idx",
                    )
                ],
            },
        ),
    ]
