# Generated by Django 5.2.14 on 2026-07-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="correctionrequest",
            name="authoritative_file_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="correctionrequest",
            name="writer_receipt_json",
            field=models.JSONField(default=dict),
        ),
    ]
