# Generated by Django 5.2.14 on 2026-08-01 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0005_review_subject_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("unchanged", "Unchanged"),
                            ("revised", "Revised"),
                            ("new", "New"),
                            ("not_reproduced", "Not reproduced"),
                        ],
                        max_length=24,
                    ),
                ),
                ("invalidated_stages_json", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["identity__economy", "identity__indicator_id"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("economy", models.CharField(max_length=120)),
                ("indicator_id", models.CharField(max_length=64)),
                ("instrument_key", models.CharField(max_length=500)),
                ("law_name", models.CharField(max_length=500)),
                ("citation_key", models.CharField(max_length=300)),
                ("finding_type", models.CharField(default="provision", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["economy", "indicator_id", "law_name", "citation_key"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("finding_key", models.CharField(max_length=64)),
                ("review_subject_hash", models.CharField(max_length=64)),
                ("revision_hash", models.CharField(max_length=64)),
                ("citation_hash", models.CharField(max_length=64)),
                ("mapping_hash", models.CharField(max_length=64)),
                ("status_hash", models.CharField(max_length=64)),
                (
                    "coverage_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("row_json", models.JSONField()),
                (
                    "proof_asset",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("blocked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="correctionrequest",
            name="review_subject_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="EvidenceChangeDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("accept", "Accept candidate revision"),
                            ("retain", "Retain current revision"),
                            ("retire", "Retire missing evidence"),
                            ("investigate", "Needs investigation"),
                        ],
                        max_length=24,
                    ),
                ),
                ("comment", models.TextField()),
                ("reviewer_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="workspace.evidencechange",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="workspace.evidencechangedecision",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceChangeSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scope_json", models.JSONField(default=list)),
                ("counts_json", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "previous_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor_change_sets",
                        to="workspace.enginesnapshot",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_evidence_change_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_change_set",
                        to="workspace.enginesnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="evidencechange",
            name="change_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="changes",
                to="workspace.evidencechangeset",
            ),
        ),
        migrations.CreateModel(
            name="EvidenceRegistryEntry",
            fields=[
                (
                    "identity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="registry_entry",
                        serialize=False,
                        to="workspace.evidenceidentity",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("not_reproduced", "Not reproduced"),
                            ("retired", "Retired"),
                        ],
                        default="current",
                        max_length=24,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["identity__economy", "identity__indicator_id"],
            },
        ),
        migrations.AddIndex(
            model_name="evidenceidentity",
            index=models.Index(
                fields=["economy", "indicator_id"],
                name="workspace_e_economy_6ca284_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceidentity",
            index=models.Index(
                fields=["instrument_key", "citation_key"],
                name="workspace_e_instrum_1451a7_idx",
            ),
        ),
        migrations.AddField(
            model_name="evidencechange",
            name="identity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="changes",
                to="workspace.evidenceidentity",
            ),
        ),
        migrations.AddField(
            model_name="evidencerevision",
            name="identity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="workspace.evidenceidentity",
            ),
        ),
        migrations.AddField(
            model_name="evidencerevision",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence_revisions",
                to="workspace.enginesnapshot",
            ),
        ),
        migrations.AddField(
            model_name="evidencechange",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_changes",
                to="workspace.evidencerevision",
            ),
        ),
        migrations.AddField(
            model_name="evidencechange",
            name="previous_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outgoing_changes",
                to="workspace.evidencerevision",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencechangedecision",
            index=models.Index(
                fields=["change", "-created_at"], name="workspace_e_change__76605f_idx"
            ),
        ),
        migrations.AddField(
            model_name="evidenceregistryentry",
            name="active_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="active_for",
                to="workspace.evidencerevision",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencerevision",
            index=models.Index(
                fields=["identity", "-created_at"],
                name="workspace_e_identit_16aa7c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencerevision",
            index=models.Index(
                fields=["finding_key", "review_subject_hash"],
                name="workspace_e_finding_b7fb1f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencerevision",
            constraint=models.UniqueConstraint(
                fields=("identity", "snapshot"),
                name="workspace_identity_snapshot_revision_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencerevision",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "finding_key"),
                name="workspace_revision_snapshot_finding_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencechange",
            constraint=models.UniqueConstraint(
                fields=("change_set", "identity"),
                name="workspace_change_set_identity_uniq",
            ),
        ),
    ]
