# Generated by Django 5.2.14 on 2026-09-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0007_engineaction_result_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="EngineWorkerHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worker_id", models.CharField(max_length=255, unique=True)),
                ("hostname", models.CharField(max_length=255)),
                ("pid", models.IntegerField()),
                ("started_at", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("current_action_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
    ]
