# Generated by Django 5.2.14 on 2026-09-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0008_engine_worker_heartbeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="engineaction",
            name="cancel_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="engineaction",
            name="cancelled_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="engineaction",
            name="cleared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="engineaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="queued",
                max_length=16,
            ),
        ),
    ]
