# Generated by Django 5.2.14 on 2026-09-27 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0009_engine_action_cancel"),
    ]

    operations = [
        migrations.CreateModel(
            name="EngineActionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveIntegerField()),
                ("ts", models.DateTimeField()),
                ("stage", models.CharField(max_length=32)),
                ("label", models.CharField(blank=True, default="", max_length=160)),
                ("level", models.CharField(default="info", max_length=8)),
                ("message", models.TextField()),
                ("detail", models.TextField(blank=True, default="")),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="workspace.engineaction",
                    ),
                ),
            ],
            options={
                "ordering": ["action", "seq"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("action", "seq"), name="workspace_action_event_seq_uniq"
                    )
                ],
            },
        ),
    ]
