# Generated by Django 5.2.14 on 2026-09-27 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0010_engine_action_events"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalReviewDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("finding_key", models.CharField(max_length=64)),
                ("review_subject_hash", models.CharField(max_length=64)),
                (
                    "queue",
                    models.CharField(
                        choices=[
                            ("new", "NEW"),
                            ("known", "KNOWN"),
                            ("absence", "Absence"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=16,
                    ),
                ),
                ("citation_checked", models.BooleanField(default=False)),
                ("mapping_checked", models.BooleanField(default=False)),
                ("status_checked", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, default="")),
                ("economy", models.CharField(blank=True, default="", max_length=64)),
                (
                    "indicator_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("law_name", models.CharField(blank=True, default="", max_length=512)),
                ("article", models.CharField(blank=True, default="", max_length=255)),
                (
                    "engine_run_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("reviewer_name", models.CharField(max_length=255)),
                ("reviewer_role", models.CharField(max_length=32)),
                ("reviewed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="workspace.engineaction",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="workspace.localreviewdecision",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["finding_key", "-created_at"],
                        name="workspace_l_finding_a18a8b_idx",
                    )
                ],
            },
        ),
    ]
