# Generated by Django 5.2.14 on 2026-09-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0011_local_review_decisions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localreviewdecision",
            name="action",
        ),
        migrations.RemoveField(
            model_name="localreviewdecision",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="localreviewdecision",
            name="supersedes",
        ),
        migrations.RemoveConstraint(
            model_name="enginesnapshot",
            name="workspace_one_active_snapshot",
        ),
        migrations.AddField(
            model_name="correctionrequest",
            name="mode",
            field=models.CharField(db_index=True, default="hybrid", max_length=16),
        ),
        migrations.AddField(
            model_name="enginesnapshot",
            name="mode",
            field=models.CharField(db_index=True, default="hybrid", max_length=16),
        ),
        migrations.AddField(
            model_name="evidenceidentity",
            name="mode",
            field=models.CharField(db_index=True, default="hybrid", max_length=16),
        ),
        migrations.AddField(
            model_name="findingdecision",
            name="mode",
            field=models.CharField(db_index=True, default="hybrid", max_length=16),
        ),
        migrations.AddField(
            model_name="recalldecision",
            name="mode",
            field=models.CharField(db_index=True, default="hybrid", max_length=16),
        ),
        migrations.AddField(
            model_name="zone3decision",
            name="mode",
            field=models.CharField(db_index=True, default="hybrid", max_length=16),
        ),
        migrations.AddConstraint(
            model_name="enginesnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("mode",),
                name="workspace_one_active_snapshot_per_mode",
            ),
        ),
        migrations.DeleteModel(
            name="LocalReviewDecision",
        ),
    ]
