# Generated by Django 5.2.14 on 2026-09-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0012_workspace_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engineaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("refresh", "Refresh"),
                    ("replay", "Replay"),
                    ("run", "Run"),
                    ("corpus", "Sources"),
                ],
                max_length=16,
            ),
        ),
    ]
